### PR TITLE
[WIP] Feature/docs: Create Swagger UI docs page

### PR DESCRIPTION
**Pull request by kabartolo**
This is a basic set of documentation for `routes/city.ts` to demonstrate most of the required fields and how the routes can be organized. The information is pulled from the source code (based on my understanding of it) so let me know if anything is missing or incorrect.

- Navigate to `/docs` to see the Swagger UI page.
- The routes are organized by user role (User, Admin, etc)
- Some object definitions are listed at the top of the `city.ts` file and referenced later using `$ref`.
- There is full information for only one error (500) for now. I'm not sure if this is the best way to present the error codes.
- To update the JSDoc comments, be sure to use 2 spaces for indentation. Tab indentation can't be read by the YAML parser, and I found the lines to be too long and difficult to format with 4-space indentation.

Questions and tasks:

- All servers need to be added to the `definitionObject` in `app.ts`. You could also add more contact info. See the [specification](https://swagger.io/specification/).
- `city.update`: Is the `countryID` parameter a path or query parameter?
- Code examples in various languages (e.g., cURL, JavaScript) still need to be added, if you want them.
- The success and error messages are copied manually from `languages/english.json`. I'm not sure if there's a way to avoid this duplication. Any ideas?
- Refactoring: More definitions can be created when all the information is in place.
- Other route files can be documented when this one is complete.

I hope this provides us with a good starting point. Let me know if you have any questions. :)

### CODE REVIEW

**Comment by gigili** [comment]
> city.update: Is the countryID parameter a path or query parameter?

It should be `req.body` param but maybe I forgot to update it. 


> The success and error messages are copied manually from languages/english.json. I'm not sure if there's a way to avoid this duplication. Any ideas?

 I don't know if there is a way to translate documentation or pull strings out of a translation file, so I for now I guess that will have to work until we find a better way.

As for the rest it looks good. Thank you.

**Comment by gigili** [comment]
@abwriting @kabartolo 
Do you want me to merge this pr or will you to continue to work on the docs by adding commit to this pr?

**Comment by kabartolo** [comment]
@gigili If you need to merge it, that's fine with me. I won't be adding any commits until later this week, and I can just create a new PR.
Thanks!

**Comment by gigili** [comment]
I am in no hurry to close it. If you would prefer to keep working on the existing one just let me know and I'll leave it open. Thank you for all the help it is really appreciated. :)

**Comment by kabartolo** [comment]
No problem at all! I need the practice :) Sure, you can keep it open for now, thank you!

**Comment by kabartolo** [comment]
Hey @gigili, do you mind checking over the errors and responses I've added?  Thanks!

I'm going to work on setting up some code examples, and I'll fix the parameters for `city.update` as well.

**Comment by kabartolo** [comment]
Oh and there's a new file in `utilities` called `typedefs.yml`, but we can change the filename or location as you like.

**Comment by kabartolo** [comment]
Hey @igor, just an update.

I couldn't find a way to add code examples for different programming languages to the Swagger UI layout. It might be possible with a custom layout, maybe something to think about for the future.

However, there is a 'Try it out' button for users to test an endpoint. We could add an 'Authorize` button by adding a security scheme to the specification (see [Swagger docs](https://swagger.io/docs/specification/authentication/)). This allows users to make real calls to the API directly from the docs page. What do you think? 

Other than that, I'm ready to merge this when you are. :)

@abwriting do you have any thoughts on the docs so far?

**Comment by kabartolo** [comment]
Great! I think this is a good start.

**Comment by gigili** [comment]
@all-contributors please add kabartolo for documentation

**Pull request merged**
