### PR TITLE
 Created a skeletal description for the actions

### PR DESCRIPTION
**Pull request by Rajakavitha1**
Just created a skeletal description for the actions.
and tagged User, Admin, and Moderator roles for the actions
tries to address https://github.com/gigili/good-food-tracker-api/issues/37

@kabartolo  Please help me understand the schemas that you have used for the request body for each action.
I am relatively new to API documentation, please let me know if any changes need to be made.

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
@gigili  and @kabartolo  please take a look and let me know if any changes need to be made.

**Review by gigili — COMMENTED** [review]
This all looks good to me, @kabartolo do you have any suggestions or feedback on this?

**Review by kabartolo — COMMENTED** [review]
@Rajakavitha1 This looks great! Please see my two comments.

Thanks so much for doing all of this work. I'm sorry for the delay. I wanted to have time to pull your branch and run the changes properly. I'm not sure if all of the error text matches the `languages/english.json` error text, but it's fine if @gigili is happy with it.

**Comment by Rajakavitha1** [comment]
Hi @kabartolo  Thanks for the review. I just incorporated the changes that you suggested. Please let me know if any other changes need to be made.

**Comment by kabartolo** [comment]
@gigili Looks good! Thank you @Rajakavitha1 !

**Comment by gigili** [comment]
@all-contributors please add @Rajakavitha1 for documentation

**Pull request merged**
